
USE gerenciadoriots;
-- GO
-- DROP TABLE IOTS
-- DROP TABLE FABRICANTES
-- DROP TABLE CATEGORIAS_IOTS

-- IF NOT EXISTS
CREATE TABLE CATEGORIAS_IOTS
(
--     ID INT NOT NULL IDENTITY(1,1)
     ID INT NOT NULL AUTO_INCREMENT
    ,CATEGORIA VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_CATEGORIA_ID PRIMARY KEY (ID)
);
-- GO


CREATE TABLE FABRICANTES
(
     ID INT NOT NULL AUTO_INCREMENT
    ,FABRICANTE VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_FABRICANTE_ID PRIMARY KEY (ID)
);
-- GO


-- CREATE TABLE IOTS
-- (
-- --     ID INT NOT NULL IDENTITY(1,1)
--      ID INT NOT NULL AUTO_INCREMENT
--     ,CATEGORIA_ID INT NOT NULL
--     ,FABRICANTE_ID INT
--     ,NOME VARCHAR(100)
--     ,LOCALIZACAO VARCHAR(100) NOT NULL
--     ,CONSTRAINT PK_IOTS_ID PRIMARY KEY (ID)
-- );
-- GO


CREATE TABLE LAMPADAS
(
--     ID INT NOT NULL IDENTITY(1,1)
     ID INT NOT NULL AUTO_INCREMENT
    ,CATEGORIA_ID INT NOT NULL
    ,FABRICANTE_ID INT
    ,NOME VARCHAR(100)
    ,LOCALIZACAO VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_LAMPADA_ID PRIMARY KEY (ID)
);
-- GO


CREATE TABLE TERMOMETROS
(
--     ID INT NOT NULL IDENTITY(1,1)
     ID INT NOT NULL AUTO_INCREMENT
    ,CATEGORIA_ID INT NOT NULL
    ,FABRICANTE_ID INT
    ,NOME VARCHAR(100)
    ,LOCALIZACAO VARCHAR(100) NOT NULL
    ,LIMITE_INFERIOR DOUBLE NOT NULL
    ,LIMITE_SUPERIOR DOUBLE NOT NULL
    ,CONSTRAINT PK_TERMOMETRO_ID PRIMARY KEY (ID)
);
-- GO


ALTER TABLE LAMPADAS
    ADD
        CONSTRAINT FK_CATEGORIA_ID
        FOREIGN KEY (CATEGORIA_ID)
        REFERENCES CATEGORIAS_IOTS (ID)

    ,ADD
        CONSTRAINT FK_FABRICANTE_ID
        FOREIGN KEY (FABRICANTE_ID)
        REFERENCES FABRICANTES (ID)
;
-- GO


ALTER TABLE TERMOMETROS
    ADD
        CONSTRAINT FK_CATEGORIA_ID
        FOREIGN KEY (CATEGORIA_ID)
        REFERENCES CATEGORIAS_IOTS (ID)

    ,ADD
        CONSTRAINT FK_FABRICANTE_ID
        FOREIGN KEY (FABRICANTE_ID)
        REFERENCES FABRICANTES (ID)
;
-- GO


INSERT INTO CATEGORIAS_IOTS VALUES(1, "LÂMPADA");
INSERT INTO CATEGORIAS_IOTS VALUES(2, "TERMÔMETRO");
INSERT INTO CATEGORIAS_IOTS VALUES(3, "WATTÍMETRO");


INSERT INTO FABRICANTES VALUES(1, "CLEBER");
INSERT INTO FABRICANTES VALUES(2, "PRESIDENTE");
INSERT INTO FABRICANTES VALUES(3, "100%");


INSERT INTO LAMPADAS VALUES(1, 1, NULL, "ABAJUR", "QUARTO");
INSERT INTO LAMPADAS VALUES(2, 1, NULL, "LUSTRE", "SALA");
INSERT INTO LAMPADAS VALUES(3, 1, NULL, "HOLOFOTE", "QUINTAL");


INSERT INTO TERMOMETROS VALUES(1, 2, 1, "", "QUARTO", 5, 35);
INSERT INTO TERMOMETROS VALUES(2, 2, 2, "", "SALA", 5, 35);
INSERT INTO TERMOMETROS VALUES(3, 2, 3, "", "COZINHA", 5, 35);


