
USE gerenciadoriots;
-- GO
-- DROP TABLE IOTS
-- DROP TABLE FABRICANTES
-- DROP TABLE CATEGORIAS_IOTS

-- IF NOT EXISTS
CREATE TABLE CATEGORIAS_IOTS
(
--     ID INT NOT NULL IDENTITY(1,1)
     ID INT NOT NULL AUTO_INCREMENT
    ,CATEGORIA VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_CATEGORIA_ID PRIMARY KEY (ID)
);
-- GO


CREATE TABLE FABRICANTES
(
     ID INT NOT NULL AUTO_INCREMENT
    ,FABRICANTE VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_FABRICANTE_ID PRIMARY KEY (ID)
);
-- GO


CREATE TABLE IOTS
(
--     ID INT NOT NULL IDENTITY(1,1)
     ID INT NOT NULL AUTO_INCREMENT
    ,CATEGORIA_ID INT NOT NULL
    ,FABRICANTE_ID INT
    ,NOME VARCHAR(100)
    ,LOCALIZACAO VARCHAR(100) NOT NULL
    ,CONSTRAINT PK_IOTS_ID PRIMARY KEY (ID)
);
-- GO


ALTER TABLE IOTS
    ADD
        CONSTRAINT FK_CATEGORIA_ID
        FOREIGN KEY (CATEGORIA_ID)
        REFERENCES CATEGORIAS_IOTS (ID)

    ,ADD
        CONSTRAINT FK_FABRICANTE_ID
        FOREIGN KEY (FABRICANTE_ID)
        REFERENCES FABRICANTES (ID)
;
-- GO


INSERT INTO CATEGORIAS_IOTS VALUES(1, "LÂMPADA");
INSERT INTO CATEGORIAS_IOTS VALUES(2, "TERMÔMETRO");
INSERT INTO CATEGORIAS_IOTS VALUES(3, "WATTÍMETRO");


INSERT INTO FABRICANTES VALUES(1, "PSC");
INSERT INTO FABRICANTES VALUES(2, "XSC");
INSERT INTO FABRICANTES VALUES(3, "YSC");


INSERT INTO IOTS VALUES(1, 1, NULL, "ABAJUR", "QUARTO");
INSERT INTO IOTS VALUES(2, 1, NULL, "LUSTRE", "SALA");
INSERT INTO IOTS VALUES(3, 1, NULL, "HOLOFOTE", "QUINTAL");
INSERT INTO IOTS VALUES(4, 2, 1, "", "QUARTO");
INSERT INTO IOTS VALUES(5, 2, 2, "", "SALA");
INSERT INTO IOTS VALUES(6, 2, 3, "", "COZINHA");


